version: '2'

services:

  db:
    image: postgres
    environment:
        POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
        POSTGRES_DB: "${POSTGRES_DB}"
        POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - 5000:5432

  web:
    build: .
    command: /bin/sh ./boot.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
